### ISSUE TITLE
Single file component can contain only one <script setup> element

### ISSUE THREAD

**Issue by dwgray** [hairyf/markdown-it-vitepress-demo#32]
I am trying to get this to be able to show demo snippets inline in documentation for a library project I'm contributing to. Is that a supported scenario? I went through the setup steps and just used the example demo container. Then the first time I inserted a demo in my *.md file, I get the following error:

```
4:25:23 PM [vitepress] Internal server error: Single file component can contain only one <script setup> element
  Plugin: vite:vue
  File: C:/Projects/bootstrap-vue-next/apps/docs/src/docs/components/accordion.md
      at createDuplicateBlockError (C:\Projects\bootstrap-vue-next\node_modules\.pnpm\@vue+compiler-sfc@3.4.27\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:1983:15)
      at C:\Projects\bootstrap-vue-next\node_modules\.pnpm\@vue+compiler-sfc@3.4.27\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:1903:21
      at Array.forEach (<anonymous>)
      at Object.parse$2 [as parse] (C:\Projects\bootstrap-vue-next\node_modules\.pnpm\@vue+compiler-sfc@3.4.27\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:1861:16)
      at createDescriptor (file:///C:/Projects/bootstrap-vue-next/node_modules/.pnpm/@vitejs+plugin-vue@5.0.4_vite@5.2.11_@types+node@20.12.12_sass@1.77.2_terser@5.30.4__vue@3.4.27_typescript@5.4.5_/node_modules/@vitejs/plugin-vue/dist/index.mjs:74:43)
      at transformMain (file:///C:/Projects/bootstrap-vue-next/node_modules/.pnpm/@vitejs+plugin-vue@5.0.4_vite@5.2.11_@types+node@20.12.12_sass@1.77.2_terser@5.30.4__vue@3.4.27_typescript@5.4.5_/node_modules/@vitejs/plugin-vue/dist/index.mjs:2367:34)
      at TransformContext.transform (file:///C:/Projects/bootstrap-vue-next/node_modules/.pnpm/@vitejs+plugin-vue@5.0.4_vite@5.2.11_@types+node@20.12.12_sass@1.77.2_terser@5.30.4__vue@3.4.27_typescript@5.4.5_/node_modules/@vitejs/plugin-vue/dist/index.mjs:2910:16)
      at Object.transform (file:///C:/Projects/bootstrap-vue-next/node_modules/.pnpm/vite@5.2.11_@types+node@20.12.12_sass@1.77.2_terser@5.30.4/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:51139:62)
      at async loadAndTransform (file:///C:/Projects/bootstrap-vue-next/node_modules/.pnpm/vite@5.2.11_@types+node@20.12.12_sass@1.77.2_terser@5.30.4/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:53894:29)
```

My *.md files all have <script setup> sections as part of the main file, so maybe that's the issue? The demo you provide in the source doesn't do that.

**Comment by dwgray** [comment]
I forked the PR to see if there was something I was doing wrong.

I was able to get the docs vitepress site working as it was.
I could add a second demo to the demos.md page and things still worked.
When I added a trivial `<script setup>` to the `demos.md` page, I started seeing the `[vitepress] Internal server error: Single file component can contain only one <script setup> element` error.
I still see the error if there is only one `<demo>` in the `demo.md` file
I put up a draft pr #33 with my experiments.

My conclusion is that there is something that you're doing with this that is incompatible with having a `<script setup>` in the *.md file. Any thoughts on if there is a way to remove this limitation (or work around it). I'd be happy to dive into fixing this, but I'm not sure where to start, so some direction would be appreciated.

Thanks!
